#card=["yasra","ali","inaya","aliyar"]
#print(card[1])numbers=[20,23,24,17,10]
#rint(numbers[::-2])
#rint(numbers)
#umbers=[]
#umbers.append(1)
#umbers.append(2)
#umbers.append(3)
#umbers.append(4)
#rint(numbers)
#numbers=[1,2,3,4,5,6,7,8,9]
#numbers[1]=28
#print(numbers)
tp=(1,)
print(tp)
a=20
y=23
a,y=y,a
print(a,y)
